require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
 AllowedMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it', 'draw', 'xit']

Style/AsciiComments:
  Enabled: false

Style/Documentation:
 Enabled: false

Style/FrozenStringLiteralComment:
 Enabled: false