version: "3.3"
services:
  db:
    container_name: rails-db
    image: postgres
    volumes:
      - /tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: julianorohde
      POSTGRES_PASSWORD: juliano123
  web:
    build: .
    container_name: rails-api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - db
